services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - movies_data:/var/lib/postgresql/data

volumes:
  movies_data:
